version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.0.0
  cryptomove: cryptomove/cryptomove@dev:alpha

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      # this `lint-pack_validate_publish-dev` workflow will run on any commit
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: cryptomove/cryptomove
          requires:
            - orb-tools/pack

      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: cryptomove/cryptomove
          release: patch
          requires:
            - orb-tools/publish-dev
